[package]
name = "legrillon"
version = "0.1.0"
edition = "2024"

[dependencies]
fltk = { version = "1.5.4", features = ["fltk-bundled"] }
fltk-theme = "0.7.5"
reqwest = "0.12.12"
tokio = { version = "1.43.0", features = ["full"] }
